name: Build and test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Install dependencies
        run: dotnet restore src
      - name: Build
        run: dotnet build src --configuration Release
      - name: Test and generate coverage report
        run: dotnet test src /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      - name: Convert coverate report to lcov format
        run: coverlet --merge=result/opencover.xml --output=result/coverage.lcov
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v1
        with:
         file: results/coverage.lcov
         token: ${{ secrets.CODECOV_TOKEN }}