name: Build and test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Install dependencies
        run: dotnet restore src
      - name: Build
        run: dotnet build src --configuration Release
      - name: Test and generate coverage report
        run: dotnet test src /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      - name: Install coverlet-coverage-report
        run: dotnet tool install -g coverlet.console
      - name: Extract code coverage percentage
        run: |
          coverage=$(cat src\tests\coverage.json | jq '.summary.totalPercentage')
          echo "$coverage"
          ls
          