name: Build and test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Install dependencies
        run: dotnet restore src
      - name: Build
        run: dotnet build src --configuration Release
      - name: Test and generate coverage report
        run: dotnet test src /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      - name: Extract code coverage percentage
        run: |
          coverlet-coverage-report -t opencover -f opencover -o coverage.json
          coverage=$(cat coverage.json | jq '.summary.totalPercentage')      
      - name: Check code coverage
        if: "coverage >= 80"
        run: echo "Code coverage is satisfactory"
      - name: Fail if code coverage is too low
        if: "coverage < 80"
        run: exit 1